### ISSUE TITLE
Creating rooms CRUD endpoints

### ISSUE THREAD

**Issue by 0xGhazy** [kaleem-project/kaleem-backend#5]
# Task description
- Implement the `/room` endpoint that deals with `POST` requests to create a new room in the database.
- Implement the `/room/{room_id}` endpoint that deals with `GET` requests to retrieve the room record from the database.
- Implement the `/room/{room_id}` endpoint that deals with `PUT` requests to update the room record from the database.
- Implement the `room/{room_id}` endpoint that deals with `DELETE` requests to delete a specific room from the database.

# Points to consider.
- All 4 endpoints must be annotated with `@token_required` from the authentication module.
- The proposed object for the room document will be available before this task is assigned.

**Comment by habibaelsayed** [comment]
Done ✅
