### ISSUE TITLE
Error in "/api/v1/forget" endpoint 

### ISSUE THREAD

**Issue by Marconoyet** [kaleem-project/kaleem-backend#6]
The message that recieved in mail doesn't have username and it's email and the link of reset password button is invalid.

**Comment by 0xGhazy** [comment]
I have fixed this issue by adding the following two lines to the main.py file.

```python
        message_body = message_body.replace("__EMAIL__", user_email)
        message_body = message_body.replace("__FIRST_NAME__", first_name)
```

![image](https://user-images.githubusercontent.com/60070427/236033367-a3b0f53b-c842-4747-9df6-26077238c472.png)
